version: "2"

services:

  misp:
    build: .
    restart: unless-stopped
    hostname: misp
    container_name: misp
    environment:
      - DB_USER=
      - DB_PASSWORD=
      - DB_HOST=
      - DB_PORT=
      - EMAIL=
      - RELAY_HOST=
      - EMAIL_USER=
      - EMAIL_PASSWORD=
      - EMAIL_PORT=
      - SITE_URL=
      - S3_KEY=
      - S3_SECRET=
      - ENV=
    ports:
      - "80:80"
